// Generated from the Unicode emoji data (version 15.1). Each entry is [emoji, searchable name].
// Single-codepoint emoji plus country flags; skin tones and multi-person (ZWJ) sequences are not included.

export interface EmojiCategory {
  id: string;
  label: string;
  icon: string;
  emojis: [string, string][];
}

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    id: "smileys",
    label: "Smileys & People",
    icon: "😀",
    emojis: [
      ["☝️", "white up pointing index"], ["☠️", "skull and crossbones"], ["☹️", "white frowning face"], ["☺️", "white smiling face"],
      ["✊", "raised fist"], ["✋", "raised hand"], ["✌️", "victory hand"], ["✍️", "writing hand"],
      ["❣️", "heavy heart exclamation mark ornament"], ["👀", "eyes"], ["👁️", "eye"], ["👂", "ear"],
      ["👃", "nose"], ["👄", "mouth"], ["👅", "tongue"], ["👆", "white up pointing backhand index"],
      ["👇", "white down pointing backhand index"], ["👈", "white left pointing backhand index"], ["👉", "white right pointing backhand index"], ["👊", "fisted hand sign"],
      ["👋", "waving hand sign"], ["👌", "ok hand sign"], ["👍", "thumbs up sign"], ["👎", "thumbs down sign"],
      ["👏", "clapping hands sign"], ["👐", "open hands sign"], ["👦", "boy"], ["👧", "girl"],
      ["👨", "man"], ["👩", "woman"], ["👪", "family"], ["👫", "man and woman holding hands"],
      ["👬", "two men holding hands"], ["👭", "two women holding hands"], ["👮", "police officer"], ["👯", "woman with bunny ears"],
      ["👰", "bride with veil"], ["👱", "person with blond hair"], ["👲", "man with gua pi mao"], ["👳", "man with turban"],
      ["👴", "older man"], ["👵", "older woman"], ["👶", "baby"], ["👷", "construction worker"],
      ["👸", "princess"], ["👹", "japanese ogre"], ["👺", "japanese goblin"], ["👻", "ghost"],
      ["👼", "baby angel"], ["👽", "extraterrestrial alien"], ["👾", "alien monster"], ["👿", "imp"],
      ["💀", "skull"], ["💁", "information desk person"], ["💂", "guardsman"], ["💃", "dancer"],
      ["💄", "lipstick"], ["💅", "nail polish"], ["💆", "face massage"], ["💇", "haircut"],
      ["💩", "pile of poo"], ["💪", "flexed biceps"], ["🕴️", "man in business suit levitating"], ["🕵️", "sleuth or spy"],
      ["🕶️", "dark sunglasses"], ["🕷️", "spider"], ["🕸️", "spider web"], ["🕹️", "joystick"],
      ["🕺", "man dancing"], ["🖐️", "raised hand with fingers splayed"], ["🖕", "reversed hand with middle finger extended"], ["🖖", "raised hand with part between middle and ring fingers"],
      ["🗣️", "speaking head in silhouette"], ["😀", "grinning face"], ["😁", "grinning face with smiling eyes"], ["😂", "face with tears of joy"],
      ["😃", "smiling face with open mouth"], ["😄", "smiling face with open mouth and smiling eyes"], ["😅", "smiling face with open mouth and cold sweat"], ["😆", "smiling face with open mouth and tightly-closed eyes"],
      ["😇", "smiling face with halo"], ["😈", "smiling face with horns"], ["😉", "winking face"], ["😊", "smiling face with smiling eyes"],
      ["😋", "face savouring delicious food"], ["😌", "relieved face"], ["😍", "smiling face with heart-shaped eyes"], ["😎", "smiling face with sunglasses"],
      ["😏", "smirking face"], ["😐", "neutral face"], ["😑", "expressionless face"], ["😒", "unamused face"],
      ["😓", "face with cold sweat"], ["😔", "pensive face"], ["😕", "confused face"], ["😖", "confounded face"],
      ["😗", "kissing face"], ["😘", "face throwing a kiss"], ["😙", "kissing face with smiling eyes"], ["😚", "kissing face with closed eyes"],
      ["😛", "face with stuck-out tongue"], ["😜", "face with stuck-out tongue and winking eye"], ["😝", "face with stuck-out tongue and tightly-closed eyes"], ["😞", "disappointed face"],
      ["😟", "worried face"], ["😠", "angry face"], ["😡", "pouting face"], ["😢", "crying face"],
      ["😣", "persevering face"], ["😤", "face with look of triumph"], ["😥", "disappointed but relieved face"], ["😦", "frowning face with open mouth"],
      ["😧", "anguished face"], ["😨", "fearful face"], ["😩", "weary face"], ["😪", "sleepy face"],
      ["😫", "tired face"], ["😬", "grimacing face"], ["😭", "loudly crying face"], ["😮", "face with open mouth"],
      ["😯", "hushed face"], ["😰", "face with open mouth and cold sweat"], ["😱", "face screaming in fear"], ["😲", "astonished face"],
      ["😳", "flushed face"], ["😴", "sleeping face"], ["😵", "dizzy face"], ["😶", "face without mouth"],
      ["😷", "face with medical mask"], ["😸", "grinning cat face with smiling eyes"], ["😹", "cat face with tears of joy"], ["😺", "smiling cat face with open mouth"],
      ["😻", "smiling cat face with heart-shaped eyes"], ["😼", "cat face with wry smile"], ["😽", "kissing cat face with closed eyes"], ["😾", "pouting cat face"],
      ["😿", "crying cat face"], ["🙀", "weary cat face"], ["🙁", "slightly frowning face"], ["🙂", "slightly smiling face"],
      ["🙃", "upside-down face"], ["🙄", "face with rolling eyes"], ["🙅", "face with no good gesture"], ["🙆", "face with ok gesture"],
      ["🙇", "person bowing deeply"], ["🙈", "see-no-evil monkey"], ["🙉", "hear-no-evil monkey"], ["🙊", "speak-no-evil monkey"],
      ["🙋", "happy person raising one hand"], ["🙌", "person raising both hands in celebration"], ["🙍", "person frowning"], ["🙎", "person with pouting face"],
      ["🙏", "person with folded hands"], ["🤐", "zipper-mouth face"], ["🤑", "money-mouth face"], ["🤒", "face with thermometer"],
      ["🤓", "nerd face"], ["🤔", "thinking face"], ["🤕", "face with head-bandage"], ["🤖", "robot face"],
      ["🤗", "hugging face"], ["🤘", "sign of the horns"], ["🤙", "call me hand"], ["🤚", "raised back of hand"],
      ["🤛", "left-facing fist"], ["🤜", "right-facing fist"], ["🤝", "handshake"], ["🤞", "hand with index and middle fingers crossed"],
      ["🤟", "i love you hand sign"], ["🤠", "face with cowboy hat"], ["🤡", "clown face"], ["🤢", "nauseated face"],
      ["🤣", "rolling on the floor laughing"], ["🤤", "drooling face"], ["🤥", "lying face"], ["🤦", "face palm"],
      ["🤧", "sneezing face"], ["🤨", "face with one eyebrow raised"], ["🤩", "grinning face with star eyes"], ["🤪", "grinning face with one large and one small eye"],
      ["🤫", "face with finger covering closed lips"], ["🤬", "serious face with symbols covering mouth"], ["🤭", "smiling face with smiling eyes and hand covering mouth"], ["🤮", "face with open mouth vomiting"],
      ["🤯", "shocked face with exploding head"], ["🤰", "pregnant woman"], ["🤱", "breast-feeding"], ["🤲", "palms up together"],
      ["🤳", "selfie"], ["🤴", "prince"], ["🤵", "man in tuxedo"], ["🤶", "mother christmas"],
      ["🤷", "shrug"], ["🤸", "person doing cartwheel"], ["🤹", "juggling"], ["🤺", "fencer"],
      ["🥰", "smiling face with smiling eyes and three hearts"], ["🥱", "yawning face"], ["🥲", "smiling face with tear"], ["🥳", "face with party horn and party hat"],
      ["🥴", "face with uneven eyes and wavy mouth"], ["🥵", "overheated face"], ["🥶", "freezing face"], ["🥷", "ninja"],
      ["🥸", "disguised face"], ["🥹", "face holding back tears"], ["🥺", "face with pleading eyes"], ["🥻", "sari"],
      ["🥼", "lab coat"], ["🥽", "goggles"], ["🥾", "hiking boot"], ["🥿", "flat shoe"],
      ["🦰", "emoji component red hair"], ["🦱", "emoji component curly hair"], ["🦲", "emoji component bald"], ["🦳", "emoji component white hair"],
      ["🦴", "bone"], ["🦵", "leg"], ["🦶", "foot"], ["🦷", "tooth"],
      ["🦸", "superhero"], ["🦹", "supervillain"], ["🦺", "safety vest"], ["🦻", "ear with hearing aid"],
      ["🦼", "motorized wheelchair"], ["🦽", "manual wheelchair"], ["🦾", "mechanical arm"], ["🦿", "mechanical leg"],
      ["🧍", "standing person"], ["🧎", "kneeling person"], ["🧏", "deaf person"], ["🧐", "face with monocle"],
      ["🧑", "adult"], ["🧒", "child"], ["🧓", "older adult"], ["🧔", "bearded person"],
      ["🧕", "person with headscarf"], ["🧖", "person in steamy room"], ["🧗", "person climbing"], ["🧘", "person in lotus position"],
      ["🧙", "mage"], ["🧚", "fairy"], ["🧛", "vampire"], ["🧜", "merperson"],
      ["🧝", "elf"], ["🧞", "genie"], ["🧟", "zombie"], ["🫀", "anatomical heart"],
      ["🫁", "lungs"], ["🫂", "people hugging"], ["🫃", "pregnant man"], ["🫄", "pregnant person"],
      ["🫅", "person with crown"], ["🫠", "melting face"], ["🫡", "saluting face"], ["🫢", "face with open eyes and hand over mouth"],
      ["🫣", "face with peeking eye"], ["🫤", "face with diagonal mouth"], ["🫥", "dotted line face"], ["🫦", "biting lip"],
      ["🫧", "bubbles"], ["🫨", "shaking face"], ["🫰", "hand with index finger and thumb crossed"], ["🫱", "rightwards hand"],
      ["🫲", "leftwards hand"], ["🫳", "palm down hand"], ["🫴", "palm up hand"], ["🫵", "index pointing at the viewer"],
      ["🫶", "heart hands"], ["🫷", "leftwards pushing hand"], ["🫸", "rightwards pushing hand"],
    ],
  },
  {
    id: "nature",
    label: "Animals & Nature",
    icon: "🐻",
    emojis: [
      ["☀️", "black sun with rays"], ["☁️", "cloud"], ["☂️", "umbrella"], ["☃️", "snowman"],
      ["☄️", "comet"], ["☔", "umbrella with rain drops"], ["☕", "hot beverage"], ["☘️", "shamrock"],
      ["⚡", "high voltage sign"], ["⛄", "snowman without snow"], ["⛅", "sun behind cloud"], ["⛈️", "thunder cloud and rain"],
      ["❄️", "snowflake"], ["🌀", "cyclone"], ["🌁", "foggy"], ["🌂", "closed umbrella"],
      ["🌃", "night with stars"], ["🌄", "sunrise over mountains"], ["🌅", "sunrise"], ["🌆", "cityscape at dusk"],
      ["🌇", "sunset over buildings"], ["🌈", "rainbow"], ["🌉", "bridge at night"], ["🌊", "water wave"],
      ["🌋", "volcano"], ["🌌", "milky way"], ["🌑", "new moon symbol"], ["🌒", "waxing crescent moon symbol"],
      ["🌓", "first quarter moon symbol"], ["🌔", "waxing gibbous moon symbol"], ["🌕", "full moon symbol"], ["🌖", "waning gibbous moon symbol"],
      ["🌗", "last quarter moon symbol"], ["🌘", "waning crescent moon symbol"], ["🌙", "crescent moon"], ["🌚", "new moon with face"],
      ["🌛", "first quarter moon with face"], ["🌜", "last quarter moon with face"], ["🌝", "full moon with face"], ["🌞", "sun with face"],
      ["🌟", "glowing star"], ["🌠", "shooting star"], ["🌤️", "white sun with small cloud"], ["🌥️", "white sun behind cloud"],
      ["🌦️", "white sun behind cloud with rain"], ["🌧️", "cloud with rain"], ["🌨️", "cloud with snow"], ["🌩️", "cloud with lightning"],
      ["🌪️", "cloud with tornado"], ["🌫️", "fog"], ["🌬️", "wind blowing face"], ["🌱", "seedling"],
      ["🌲", "evergreen tree"], ["🌳", "deciduous tree"], ["🌴", "palm tree"], ["🌵", "cactus"],
      ["🌶️", "hot pepper"], ["🌷", "tulip"], ["🌸", "cherry blossom"], ["🌹", "rose"],
      ["🌺", "hibiscus"], ["🌻", "sunflower"], ["🌼", "blossom"], ["🌽", "ear of maize"],
      ["🌾", "ear of rice"], ["🌿", "herb"], ["🍀", "four leaf clover"], ["🍁", "maple leaf"],
      ["🍂", "fallen leaf"], ["🍃", "leaf fluttering in wind"], ["🍄", "mushroom"], ["🏵️", "rosette"],
      ["🐀", "rat"], ["🐁", "mouse"], ["🐂", "ox"], ["🐃", "water buffalo"],
      ["🐄", "cow"], ["🐅", "tiger"], ["🐆", "leopard"], ["🐇", "rabbit"],
      ["🐈", "cat"], ["🐉", "dragon"], ["🐊", "crocodile"], ["🐋", "whale"],
      ["🐌", "snail"], ["🐍", "snake"], ["🐎", "horse"], ["🐏", "ram"],
      ["🐐", "goat"], ["🐑", "sheep"], ["🐒", "monkey"], ["🐓", "rooster"],
      ["🐔", "chicken"], ["🐕", "dog"], ["🐖", "pig"], ["🐗", "boar"],
      ["🐘", "elephant"], ["🐙", "octopus"], ["🐚", "spiral shell"], ["🐛", "bug"],
      ["🐜", "ant"], ["🐝", "honeybee"], ["🐞", "lady beetle"], ["🐟", "fish"],
      ["🐠", "tropical fish"], ["🐡", "blowfish"], ["🐢", "turtle"], ["🐣", "hatching chick"],
      ["🐤", "baby chick"], ["🐥", "front-facing baby chick"], ["🐦", "bird"], ["🐧", "penguin"],
      ["🐨", "koala"], ["🐩", "poodle"], ["🐪", "dromedary camel"], ["🐫", "bactrian camel"],
      ["🐬", "dolphin"], ["🐭", "mouse face"], ["🐮", "cow face"], ["🐯", "tiger face"],
      ["🐰", "rabbit face"], ["🐱", "cat face"], ["🐲", "dragon face"], ["🐳", "spouting whale"],
      ["🐴", "horse face"], ["🐵", "monkey face"], ["🐶", "dog face"], ["🐷", "pig face"],
      ["🐸", "frog face"], ["🐹", "hamster face"], ["🐺", "wolf face"], ["🐻", "bear face"],
      ["🐼", "panda face"], ["🐽", "pig nose"], ["🐾", "paw prints"], ["🐿️", "chipmunk"],
      ["💐", "bouquet"], ["💥", "collision symbol"], ["💧", "droplet"], ["💫", "dizzy symbol"],
      ["💮", "white flower"], ["🔥", "fire"], ["🕊️", "dove of peace"], ["🥀", "wilted flower"],
      ["🦀", "crab"], ["🦁", "lion face"], ["🦂", "scorpion"], ["🦃", "turkey"],
      ["🦄", "unicorn face"], ["🦅", "eagle"], ["🦆", "duck"], ["🦇", "bat"],
      ["🦈", "shark"], ["🦉", "owl"], ["🦊", "fox face"], ["🦋", "butterfly"],
      ["🦌", "deer"], ["🦍", "gorilla"], ["🦎", "lizard"], ["🦏", "rhinoceros"],
      ["🦐", "shrimp"], ["🦑", "squid"], ["🦒", "giraffe face"], ["🦓", "zebra face"],
      ["🦔", "hedgehog"], ["🦕", "sauropod"], ["🦖", "t-rex"], ["🦗", "cricket"],
      ["🦘", "kangaroo"], ["🦙", "llama"], ["🦚", "peacock"], ["🦛", "hippopotamus"],
      ["🦜", "parrot"], ["🦝", "raccoon"], ["🦞", "lobster"], ["🦟", "mosquito"],
      ["🦠", "microbe"], ["🦡", "badger"], ["🦢", "swan"], ["🦣", "mammoth"],
      ["🦤", "dodo"], ["🦥", "sloth"], ["🦦", "otter"], ["🦧", "orangutan"],
      ["🦨", "skunk"], ["🦩", "flamingo"], ["🦪", "oyster"], ["🦫", "beaver"],
      ["🦬", "bison"], ["🦭", "seal"], ["🦮", "guide dog"], ["🪰", "fly"],
      ["🪱", "worm"], ["🪲", "beetle"], ["🪳", "cockroach"], ["🪴", "potted plant"],
      ["🪵", "wood"], ["🪶", "feather"], ["🪷", "lotus"], ["🪸", "coral"],
      ["🪹", "empty nest"], ["🪺", "nest with eggs"], ["🪻", "hyacinth"], ["🪼", "jellyfish"],
      ["🪽", "wing"], ["🪿", "goose"], ["🫐", "blueberries"], ["🫑", "bell pepper"],
      ["🫒", "olive"], ["🫓", "flatbread"], ["🫔", "tamale"], ["🫕", "fondue"],
      ["🫖", "teapot"], ["🫗", "pouring liquid"], ["🫘", "beans"], ["🫙", "jar"],
      ["🫚", "ginger root"], ["🫛", "pea pod"],
    ],
  },
  {
    id: "food",
    label: "Food & Drink",
    icon: "🍔",
    emojis: [
      ["🌭", "hot dog"], ["🌮", "taco"], ["🌯", "burrito"], ["🌰", "chestnut"],
      ["🍅", "tomato"], ["🍆", "aubergine"], ["🍇", "grapes"], ["🍈", "melon"],
      ["🍉", "watermelon"], ["🍊", "tangerine"], ["🍋", "lemon"], ["🍌", "banana"],
      ["🍍", "pineapple"], ["🍎", "red apple"], ["🍏", "green apple"], ["🍐", "pear"],
      ["🍑", "peach"], ["🍒", "cherries"], ["🍓", "strawberry"], ["🍔", "hamburger"],
      ["🍕", "slice of pizza"], ["🍖", "meat on bone"], ["🍗", "poultry leg"], ["🍘", "rice cracker"],
      ["🍙", "rice ball"], ["🍚", "cooked rice"], ["🍛", "curry and rice"], ["🍜", "steaming bowl"],
      ["🍝", "spaghetti"], ["🍞", "bread"], ["🍟", "french fries"], ["🍠", "roasted sweet potato"],
      ["🍡", "dango"], ["🍢", "oden"], ["🍣", "sushi"], ["🍤", "fried shrimp"],
      ["🍥", "fish cake with swirl design"], ["🍦", "soft ice cream"], ["🍧", "shaved ice"], ["🍨", "ice cream"],
      ["🍩", "doughnut"], ["🍪", "cookie"], ["🍫", "chocolate bar"], ["🍬", "candy"],
      ["🍭", "lollipop"], ["🍮", "custard"], ["🍯", "honey pot"], ["🍰", "shortcake"],
      ["🍱", "bento box"], ["🍲", "pot of food"], ["🍳", "cooking"], ["🍴", "fork and knife"],
      ["🍵", "teacup without handle"], ["🍶", "sake bottle and cup"], ["🍷", "wine glass"], ["🍸", "cocktail glass"],
      ["🍹", "tropical drink"], ["🍺", "beer mug"], ["🍻", "clinking beer mugs"], ["🍼", "baby bottle"],
      ["🍽️", "fork and knife with plate"], ["🍾", "bottle with popping cork"], ["🍿", "popcorn"], ["🥄", "spoon"],
      ["🥐", "croissant"], ["🥑", "avocado"], ["🥒", "cucumber"], ["🥓", "bacon"],
      ["🥔", "potato"], ["🥕", "carrot"], ["🥖", "baguette bread"], ["🥗", "green salad"],
      ["🥘", "shallow pan of food"], ["🥙", "stuffed flatbread"], ["🥚", "egg"], ["🥛", "glass of milk"],
      ["🥜", "peanuts"], ["🥝", "kiwifruit"], ["🥞", "pancakes"], ["🥟", "dumpling"],
      ["🥠", "fortune cookie"], ["🥡", "takeout box"], ["🥢", "chopsticks"], ["🥣", "bowl with spoon"],
      ["🥤", "cup with straw"], ["🥥", "coconut"], ["🥦", "broccoli"], ["🥧", "pie"],
      ["🥨", "pretzel"], ["🥩", "cut of meat"], ["🥪", "sandwich"], ["🥫", "canned food"],
      ["🥬", "leafy green"], ["🥭", "mango"], ["🥮", "moon cake"], ["🥯", "bagel"],
      ["🧀", "cheese wedge"], ["🧁", "cupcake"], ["🧂", "salt shaker"], ["🧃", "beverage box"],
      ["🧄", "garlic"], ["🧅", "onion"], ["🧆", "falafel"], ["🧇", "waffle"],
      ["🧈", "butter"], ["🧉", "mate drink"], ["🧊", "ice cube"], ["🧋", "bubble tea"],
      ["🧌", "troll"],
    ],
  },
  {
    id: "activities",
    label: "Activities",
    icon: "⚽",
    emojis: [
      ["♟️", "black chess pawn"], ["⚽", "soccer ball"], ["⚾", "baseball"], ["⛳", "flag in hole"],
      ["⛸️", "ice skate"], ["🀄", "mahjong tile red dragon"], ["🃏", "playing card black joker"], ["🎃", "jack-o-lantern"],
      ["🎄", "christmas tree"], ["🎅", "father christmas"], ["🎆", "fireworks"], ["🎇", "firework sparkler"],
      ["🎈", "balloon"], ["🎉", "party popper"], ["🎊", "confetti ball"], ["🎋", "tanabata tree"],
      ["🎍", "pine decoration"], ["🎎", "japanese dolls"], ["🎏", "carp streamer"], ["🎐", "wind chime"],
      ["🎑", "moon viewing ceremony"], ["🎒", "school satchel"], ["🎓", "graduation cap"], ["🎖️", "military medal"],
      ["🎗️", "reminder ribbon"], ["🎞️", "film frames"], ["🎟️", "admission tickets"], ["🎠", "carousel horse"],
      ["🎡", "ferris wheel"], ["🎢", "roller coaster"], ["🎣", "fishing pole and fish"], ["🎤", "microphone"],
      ["🎥", "movie camera"], ["🎦", "cinema"], ["🎧", "headphone"], ["🎨", "artist palette"],
      ["🎩", "top hat"], ["🎪", "circus tent"], ["🎫", "ticket"], ["🎬", "clapper board"],
      ["🎭", "performing arts"], ["🎮", "video game"], ["🎯", "direct hit"], ["🎰", "slot machine"],
      ["🎱", "billiards"], ["🎲", "game die"], ["🎳", "bowling"], ["🎴", "flower playing cards"],
      ["🎵", "musical note"], ["🎶", "multiple musical notes"], ["🎷", "saxophone"], ["🎸", "guitar"],
      ["🎹", "musical keyboard"], ["🎺", "trumpet"], ["🎻", "violin"], ["🎼", "musical score"],
      ["🎽", "running shirt with sash"], ["🎾", "tennis racquet and ball"], ["🎿", "ski and ski boot"], ["🏀", "basketball and hoop"],
      ["🏂", "snowboarder"], ["🏃", "runner"], ["🏄", "surfer"], ["🏅", "sports medal"],
      ["🏆", "trophy"], ["🏇", "horse racing"], ["🏈", "american football"], ["🏉", "rugby football"],
      ["🏊", "swimmer"], ["🏏", "cricket bat and ball"], ["🏐", "volleyball"], ["🏑", "field hockey stick and ball"],
      ["🏒", "ice hockey stick and puck"], ["🏓", "table tennis paddle and ball"], ["🏮", "izakaya lantern"], ["🏸", "badminton racquet and shuttlecock"],
      ["🏹", "bow and arrow"], ["🤼", "wrestlers"], ["🤽", "water polo"], ["🤾", "handball"],
      ["🤿", "diving mask"], ["🥁", "drum with drumsticks"], ["🥂", "clinking glasses"], ["🥃", "tumbler glass"],
      ["🥅", "goal net"], ["🥇", "first place medal"], ["🥈", "second place medal"], ["🥉", "third place medal"],
      ["🥊", "boxing glove"], ["🥋", "martial arts uniform"], ["🥌", "curling stone"], ["🥍", "lacrosse stick and ball"],
      ["🥎", "softball"], ["🥏", "flying disc"], ["🧩", "jigsaw puzzle piece"], ["🪀", "yo-yo"],
      ["🪁", "kite"], ["🪂", "parachute"], ["🪃", "boomerang"], ["🪄", "magic wand"],
      ["🪅", "pinata"], ["🪆", "nesting dolls"], ["🪇", "maracas"], ["🪈", "flute"],
    ],
  },
  {
    id: "travel",
    label: "Travel & Places",
    icon: "🚗",
    emojis: [
      ["♨️", "hot springs"], ["⚓", "anchor"], ["⛩️", "shinto shrine"], ["⛪", "church"],
      ["⛰️", "mountain"], ["⛱️", "umbrella on ground"], ["⛲", "fountain"], ["⛴️", "ferry"],
      ["⛵", "sailboat"], ["⛷️", "skier"], ["⛹️", "person with ball"], ["⛺", "tent"],
      ["⛽", "fuel pump"], ["✈️", "airplane"], ["🌍", "earth globe europe-africa"], ["🌎", "earth globe americas"],
      ["🌏", "earth globe asia-australia"], ["🌐", "globe with meridians"], ["🏔️", "snow capped mountain"], ["🏕️", "camping"],
      ["🏖️", "beach with umbrella"], ["🏗️", "building construction"], ["🏘️", "house buildings"], ["🏙️", "cityscape"],
      ["🏚️", "derelict house building"], ["🏛️", "classical building"], ["🏜️", "desert"], ["🏝️", "desert island"],
      ["🏞️", "national park"], ["🏟️", "stadium"], ["🏠", "house building"], ["🏡", "house with garden"],
      ["🏢", "office building"], ["🏣", "japanese post office"], ["🏤", "european post office"], ["🏥", "hospital"],
      ["🏦", "bank"], ["🏧", "automated teller machine"], ["🏨", "hotel"], ["🏩", "love hotel"],
      ["🏪", "convenience store"], ["🏫", "school"], ["🏬", "department store"], ["🏭", "factory"],
      ["🏯", "japanese castle"], ["🏰", "european castle"], ["🗺️", "world map"], ["🗻", "mount fuji"],
      ["🗼", "tokyo tower"], ["🗽", "statue of liberty"], ["🗾", "silhouette of japan"], ["🗿", "moyai"],
      ["🚀", "rocket"], ["🚁", "helicopter"], ["🚂", "steam locomotive"], ["🚃", "railway car"],
      ["🚄", "high-speed train"], ["🚅", "high-speed train with bullet nose"], ["🚆", "train"], ["🚇", "metro"],
      ["🚈", "light rail"], ["🚉", "station"], ["🚊", "tram"], ["🚋", "tram car"],
      ["🚌", "bus"], ["🚍", "oncoming bus"], ["🚎", "trolleybus"], ["🚏", "bus stop"],
      ["🚐", "minibus"], ["🚑", "ambulance"], ["🚒", "fire engine"], ["🚓", "police car"],
      ["🚔", "oncoming police car"], ["🚕", "taxi"], ["🚖", "oncoming taxi"], ["🚗", "automobile"],
      ["🚘", "oncoming automobile"], ["🚙", "recreational vehicle"], ["🚚", "delivery truck"], ["🚛", "articulated lorry"],
      ["🚜", "tractor"], ["🚝", "monorail"], ["🚞", "mountain railway"], ["🚟", "suspension railway"],
      ["🚠", "mountain cableway"], ["🚡", "aerial tramway"], ["🚢", "ship"], ["🚣", "rowboat"],
      ["🚤", "speedboat"], ["🚥", "horizontal traffic light"], ["🚦", "vertical traffic light"], ["🚧", "construction sign"],
      ["🚨", "police cars revolving light"], ["🚪", "door"], ["🚫", "no entry sign"], ["🚬", "smoking symbol"],
      ["🚭", "no smoking symbol"], ["🚮", "put litter in its place symbol"], ["🚯", "do not litter symbol"], ["🚰", "potable water symbol"],
      ["🚱", "non-potable water symbol"], ["🚲", "bicycle"], ["🚳", "no bicycles"], ["🚴", "bicyclist"],
      ["🚵", "mountain bicyclist"], ["🚶", "pedestrian"], ["🚷", "no pedestrians"], ["🚸", "children crossing"],
      ["🚹", "mens symbol"], ["🚺", "womens symbol"], ["🚻", "restroom"], ["🚼", "baby symbol"],
      ["🚽", "toilet"], ["🚾", "water closet"], ["🚿", "shower"], ["🛀", "bath"],
      ["🛁", "bathtub"], ["🛂", "passport control"], ["🛃", "customs"], ["🛄", "baggage claim"],
      ["🛅", "left luggage"], ["🛋️", "couch and lamp"], ["🛌", "sleeping accommodation"], ["🛍️", "shopping bags"],
      ["🛎️", "bellhop bell"], ["🛏️", "bed"], ["🛐", "place of worship"], ["🛑", "octagonal sign"],
      ["🛒", "shopping trolley"], ["🛕", "hindu temple"], ["🛖", "hut"], ["🛗", "elevator"],
      ["🛜", "wireless"], ["🛝", "playground slide"], ["🛞", "wheel"], ["🛟", "ring buoy"],
      ["🛠️", "hammer and wrench"], ["🛡️", "shield"], ["🛢️", "oil drum"], ["🛣️", "motorway"],
      ["🛤️", "railway track"], ["🛥️", "motor boat"], ["🛩️", "small airplane"], ["🛫", "airplane departure"],
      ["🛬", "airplane arriving"], ["🛰️", "satellite"], ["🛳️", "passenger ship"], ["🛴", "scooter"],
      ["🛵", "motor scooter"], ["🛶", "canoe"], ["🛷", "sled"], ["🛸", "flying saucer"],
      ["🛹", "skateboard"], ["🛺", "auto rickshaw"], ["🛻", "pickup truck"], ["🛼", "roller skate"],
      ["🧭", "compass"],
    ],
  },
  {
    id: "objects",
    label: "Objects",
    icon: "💡",
    emojis: [
      ["⌚", "watch"], ["⌛", "hourglass"], ["⌨️", "keyboard"], ["⏰", "alarm clock"],
      ["⏱️", "stopwatch"], ["⏲️", "timer clock"], ["⏳", "hourglass with flowing sand"], ["☎️", "black telephone"],
      ["⚒️", "hammer and pick"], ["⚔️", "crossed swords"], ["⚕️", "staff of aesculapius"], ["⚖️", "scales"],
      ["⚗️", "alembic"], ["⚙️", "gear"], ["⚛️", "atom symbol"], ["⚜️", "fleur-de-lis"],
      ["⚰️", "coffin"], ["⚱️", "funeral urn"], ["⛑️", "helmet with white cross"], ["⛓️", "chains"],
      ["✂️", "black scissors"], ["✉️", "envelope"], ["✏️", "pencil"], ["✒️", "black nib"],
      ["🏺", "amphora"], ["👑", "crown"], ["👒", "womans hat"], ["👓", "eyeglasses"],
      ["👔", "necktie"], ["👕", "t-shirt"], ["👖", "jeans"], ["👗", "dress"],
      ["👘", "kimono"], ["👙", "bikini"], ["👚", "womans clothes"], ["👛", "purse"],
      ["👜", "handbag"], ["👝", "pouch"], ["👞", "mans shoe"], ["👟", "athletic shoe"],
      ["👠", "high-heeled shoe"], ["👡", "womans sandal"], ["👢", "womans boots"], ["👣", "footprints"],
      ["👤", "bust in silhouette"], ["👥", "busts in silhouette"], ["💈", "barber pole"], ["💉", "syringe"],
      ["💊", "pill"], ["💋", "kiss mark"], ["💌", "love letter"], ["💍", "ring"],
      ["💎", "gem stone"], ["💏", "kiss"], ["💑", "couple with heart"], ["💒", "wedding"],
      ["💓", "beating heart"], ["💔", "broken heart"], ["💕", "two hearts"], ["💖", "sparkling heart"],
      ["💗", "growing heart"], ["💘", "heart with arrow"], ["💙", "blue heart"], ["💚", "green heart"],
      ["💛", "yellow heart"], ["💜", "purple heart"], ["💝", "heart with ribbon"], ["💞", "revolving hearts"],
      ["💟", "heart decoration"], ["💠", "diamond shape with a dot inside"], ["💡", "electric light bulb"], ["💢", "anger symbol"],
      ["💣", "bomb"], ["💤", "sleeping symbol"], ["💦", "splashing sweat symbol"], ["💨", "dash symbol"],
      ["💬", "speech balloon"], ["💭", "thought balloon"], ["💯", "hundred points symbol"], ["💰", "money bag"],
      ["💱", "currency exchange"], ["💲", "heavy dollar sign"], ["💳", "credit card"], ["💴", "banknote with yen sign"],
      ["💵", "banknote with dollar sign"], ["💶", "banknote with euro sign"], ["💷", "banknote with pound sign"], ["💸", "money with wings"],
      ["💹", "chart with upwards trend and yen sign"], ["💺", "seat"], ["💻", "personal computer"], ["💼", "briefcase"],
      ["💽", "minidisc"], ["💾", "floppy disk"], ["💿", "optical disc"], ["📀", "dvd"],
      ["📁", "file folder"], ["📂", "open file folder"], ["📃", "page with curl"], ["📄", "page facing up"],
      ["📅", "calendar"], ["📆", "tear-off calendar"], ["📇", "card index"], ["📈", "chart with upwards trend"],
      ["📉", "chart with downwards trend"], ["📊", "bar chart"], ["📋", "clipboard"], ["📌", "pushpin"],
      ["📍", "round pushpin"], ["📎", "paperclip"], ["📏", "straight ruler"], ["📐", "triangular ruler"],
      ["📑", "bookmark tabs"], ["📒", "ledger"], ["📓", "notebook"], ["📔", "notebook with decorative cover"],
      ["📕", "closed book"], ["📖", "open book"], ["📗", "green book"], ["📘", "blue book"],
      ["📙", "orange book"], ["📚", "books"], ["📛", "name badge"], ["📜", "scroll"],
      ["📝", "memo"], ["📞", "telephone receiver"], ["📟", "pager"], ["📠", "fax machine"],
      ["📡", "satellite antenna"], ["📢", "public address loudspeaker"], ["📣", "cheering megaphone"], ["📤", "outbox tray"],
      ["📥", "inbox tray"], ["📦", "package"], ["📧", "e-mail symbol"], ["📨", "incoming envelope"],
      ["📩", "envelope with downwards arrow above"], ["📪", "closed mailbox with lowered flag"], ["📫", "closed mailbox with raised flag"], ["📬", "open mailbox with raised flag"],
      ["📭", "open mailbox with lowered flag"], ["📮", "postbox"], ["📯", "postal horn"], ["📰", "newspaper"],
      ["📱", "mobile phone"], ["📲", "mobile phone with rightwards arrow at left"], ["📳", "vibration mode"], ["📴", "mobile phone off"],
      ["📵", "no mobile phones"], ["📶", "antenna with bars"], ["📷", "camera"], ["📸", "camera with flash"],
      ["📹", "video camera"], ["📺", "television"], ["📻", "radio"], ["📼", "videocassette"],
      ["📽️", "film projector"], ["📿", "prayer beads"], ["🖇️", "linked paperclips"], ["🖊️", "lower left ballpoint pen"],
      ["🖋️", "lower left fountain pen"], ["🖌️", "lower left paintbrush"], ["🖍️", "lower left crayon"], ["🖥️", "desktop computer"],
      ["🖨️", "printer"], ["🖱️", "three button mouse"], ["🖲️", "trackball"], ["🖼️", "frame with picture"],
      ["🗂️", "card index dividers"], ["🗃️", "card file box"], ["🗄️", "file cabinet"], ["🗑️", "wastebasket"],
      ["🗒️", "spiral note pad"], ["🗓️", "spiral calendar pad"], ["🗜️", "compression"], ["🗝️", "old key"],
      ["🗞️", "rolled-up newspaper"], ["🗡️", "dagger knife"], ["🗨️", "left speech bubble"], ["🗯️", "right anger bubble"],
      ["🗳️", "ballot box with ballot"], ["🧠", "brain"], ["🧡", "orange heart"], ["🧢", "billed cap"],
      ["🧣", "scarf"], ["🧤", "gloves"], ["🧥", "coat"], ["🧦", "socks"],
      ["🧧", "red gift envelope"], ["🧨", "firecracker"], ["🧪", "test tube"], ["🧫", "petri dish"],
      ["🧬", "dna double helix"], ["🧮", "abacus"], ["🧯", "fire extinguisher"], ["🧰", "toolbox"],
      ["🧱", "brick"], ["🧲", "magnet"], ["🧳", "luggage"], ["🧴", "lotion bottle"],
      ["🧵", "spool of thread"], ["🧶", "ball of yarn"], ["🧷", "safety pin"], ["🧸", "teddy bear"],
      ["🧹", "broom"], ["🧺", "basket"], ["🧻", "roll of paper"], ["🧼", "bar of soap"],
      ["🧽", "sponge"], ["🧾", "receipt"], ["🧿", "nazar amulet"], ["🪐", "ringed planet"],
      ["🪑", "chair"], ["🪒", "razor"], ["🪓", "axe"], ["🪔", "diya lamp"],
      ["🪕", "banjo"], ["🪖", "military helmet"], ["🪗", "accordion"], ["🪘", "long drum"],
      ["🪙", "coin"], ["🪚", "carpentry saw"], ["🪛", "screwdriver"], ["🪜", "ladder"],
      ["🪝", "hook"], ["🪞", "mirror"], ["🪟", "window"], ["🪠", "plunger"],
      ["🪡", "sewing needle"], ["🪢", "knot"], ["🪣", "bucket"], ["🪤", "mouse trap"],
      ["🪥", "toothbrush"], ["🪦", "headstone"], ["🪧", "placard"], ["🪨", "rock"],
      ["🪩", "mirror ball"], ["🪪", "identification card"], ["🪫", "low battery"], ["🪬", "hamsa"],
      ["🪭", "folding hand fan"], ["🪮", "hair pick"], ["🪯", "khanda"],
    ],
  },
  {
    id: "symbols",
    label: "Symbols",
    icon: "❤️",
    emojis: [
      ["©️", "copyright sign"], ["®️", "registered sign"], ["‼️", "double exclamation mark"], ["⁉️", "exclamation question mark"],
      ["™️", "trade mark sign"], ["ℹ️", "information source"], ["↔️", "left right arrow"], ["↕️", "up down arrow"],
      ["↖️", "north west arrow"], ["↗️", "north east arrow"], ["↘️", "south east arrow"], ["↙️", "south west arrow"],
      ["↩️", "leftwards arrow with hook"], ["↪️", "rightwards arrow with hook"], ["⏏️", "eject symbol"], ["⏩", "black right-pointing double triangle"],
      ["⏪", "black left-pointing double triangle"], ["⏫", "black up-pointing double triangle"], ["⏬", "black down-pointing double triangle"], ["⏭️", "black right-pointing double triangle with vertical bar"],
      ["⏮️", "black left-pointing double triangle with vertical bar"], ["⏯️", "black right-pointing triangle with double vertical bar"], ["⏸️", "double vertical bar"], ["⏹️", "black square for stop"],
      ["⏺️", "black circle for record"], ["Ⓜ️", "circled latin capital letter m"], ["▪️", "black small square"], ["▫️", "white small square"],
      ["▶️", "black right-pointing triangle"], ["◀️", "black left-pointing triangle"], ["◻️", "white medium square"], ["◼️", "black medium square"],
      ["◽", "white medium small square"], ["◾", "black medium small square"], ["☑️", "ballot box with check"], ["☢️", "radioactive sign"],
      ["☣️", "biohazard sign"], ["☦️", "orthodox cross"], ["☪️", "star and crescent"], ["☮️", "peace symbol"],
      ["☯️", "yin yang"], ["☸️", "wheel of dharma"], ["♀️", "female sign"], ["♂️", "male sign"],
      ["♈", "aries"], ["♉", "taurus"], ["♊", "gemini"], ["♋", "cancer"],
      ["♌", "leo"], ["♍", "virgo"], ["♎", "libra"], ["♏", "scorpius"],
      ["♐", "sagittarius"], ["♑", "capricorn"], ["♒", "aquarius"], ["♓", "pisces"],
      ["♠️", "black spade suit"], ["♣️", "black club suit"], ["♥️", "black heart suit"], ["♦️", "black diamond suit"],
      ["♻️", "black universal recycling symbol"], ["♾️", "permanent paper sign"], ["♿", "wheelchair symbol"], ["⚠️", "warning sign"],
      ["⚧️", "male with stroke and male and female sign"], ["⚪", "medium white circle"], ["⚫", "medium black circle"], ["⛎", "ophiuchus"],
      ["⛏️", "pick"], ["⛔", "no entry"], ["✅", "white heavy check mark"], ["✔️", "heavy check mark"],
      ["✖️", "heavy multiplication x"], ["✝️", "latin cross"], ["✡️", "star of david"], ["✨", "sparkles"],
      ["✳️", "eight spoked asterisk"], ["✴️", "eight pointed black star"], ["❇️", "sparkle"], ["❌", "cross mark"],
      ["❎", "negative squared cross mark"], ["❓", "black question mark ornament"], ["❔", "white question mark ornament"], ["❕", "white exclamation mark ornament"],
      ["❗", "heavy exclamation mark symbol"], ["❤️", "heavy black heart"], ["➕", "heavy plus sign"], ["➖", "heavy minus sign"],
      ["➗", "heavy division sign"], ["➡️", "black rightwards arrow"], ["➰", "curly loop"], ["➿", "double curly loop"],
      ["⤴️", "arrow pointing rightwards then curving upwards"], ["⤵️", "arrow pointing rightwards then curving downwards"], ["⬅️", "leftwards black arrow"], ["⬆️", "upwards black arrow"],
      ["⬇️", "downwards black arrow"], ["⬛", "black large square"], ["⬜", "white large square"], ["⭐", "white medium star"],
      ["⭕", "heavy large circle"], ["〰️", "wavy dash"], ["〽️", "part alternation mark"], ["㊗️", "circled ideograph congratulation"],
      ["㊙️", "circled ideograph secret"], ["🅰️", "negative squared latin capital letter a"], ["🅱️", "negative squared latin capital letter b"], ["🅾️", "negative squared latin capital letter o"],
      ["🅿️", "negative squared latin capital letter p"], ["🆎", "negative squared ab"], ["🆑", "squared cl"], ["🆒", "squared cool"],
      ["🆓", "squared free"], ["🆔", "squared id"], ["🆕", "squared new"], ["🆖", "squared ng"],
      ["🆗", "squared ok"], ["🆘", "squared sos"], ["🆙", "squared up with exclamation mark"], ["🆚", "squared vs"],
      ["🈁", "squared katakana koko"], ["🈂️", "squared katakana sa"], ["🈚", "squared cjk unified ideograph-7121"], ["🈯", "squared cjk unified ideograph-6307"],
      ["🈲", "squared cjk unified ideograph-7981"], ["🈳", "squared cjk unified ideograph-7a7a"], ["🈴", "squared cjk unified ideograph-5408"], ["🈵", "squared cjk unified ideograph-6e80"],
      ["🈶", "squared cjk unified ideograph-6709"], ["🈷️", "squared cjk unified ideograph-6708"], ["🈸", "squared cjk unified ideograph-7533"], ["🈹", "squared cjk unified ideograph-5272"],
      ["🈺", "squared cjk unified ideograph-55b6"], ["🉐", "circled ideograph advantage"], ["🉑", "circled ideograph accept"], ["🌡️", "thermometer"],
      ["🎀", "ribbon"], ["🎁", "wrapped present"], ["🎂", "birthday cake"], ["🎙️", "studio microphone"],
      ["🎚️", "level slider"], ["🎛️", "control knobs"], ["🏋️", "weight lifter"], ["🏌️", "golfer"],
      ["🏍️", "racing motorcycle"], ["🏎️", "racing car"], ["🏷️", "label"], ["🔀", "twisted rightwards arrows"],
      ["🔁", "clockwise rightwards and leftwards open circle arrows"], ["🔂", "clockwise rightwards and leftwards open circle arrows with circled one overlay"], ["🔃", "clockwise downwards and upwards open circle arrows"], ["🔄", "anticlockwise downwards and upwards open circle arrows"],
      ["🔅", "low brightness symbol"], ["🔆", "high brightness symbol"], ["🔇", "speaker with cancellation stroke"], ["🔈", "speaker"],
      ["🔉", "speaker with one sound wave"], ["🔊", "speaker with three sound waves"], ["🔋", "battery"], ["🔌", "electric plug"],
      ["🔍", "left-pointing magnifying glass"], ["🔎", "right-pointing magnifying glass"], ["🔏", "lock with ink pen"], ["🔐", "closed lock with key"],
      ["🔑", "key"], ["🔒", "lock"], ["🔓", "open lock"], ["🔔", "bell"],
      ["🔕", "bell with cancellation stroke"], ["🔖", "bookmark"], ["🔗", "link symbol"], ["🔘", "radio button"],
      ["🔙", "back with leftwards arrow above"], ["🔚", "end with leftwards arrow above"], ["🔛", "on with exclamation mark with left right arrow above"], ["🔜", "soon with rightwards arrow above"],
      ["🔝", "top with upwards arrow above"], ["🔞", "no one under eighteen symbol"], ["🔟", "keycap ten"], ["🔠", "input symbol for latin capital letters"],
      ["🔡", "input symbol for latin small letters"], ["🔢", "input symbol for numbers"], ["🔣", "input symbol for symbols"], ["🔤", "input symbol for latin letters"],
      ["🔦", "electric torch"], ["🔧", "wrench"], ["🔨", "hammer"], ["🔩", "nut and bolt"],
      ["🔪", "hocho"], ["🔫", "pistol"], ["🔬", "microscope"], ["🔭", "telescope"],
      ["🔮", "crystal ball"], ["🔯", "six pointed star with middle dot"], ["🔰", "japanese symbol for beginner"], ["🔱", "trident emblem"],
      ["🔲", "black square button"], ["🔳", "white square button"], ["🔴", "large red circle"], ["🔵", "large blue circle"],
      ["🔶", "large orange diamond"], ["🔷", "large blue diamond"], ["🔸", "small orange diamond"], ["🔹", "small blue diamond"],
      ["🔺", "up-pointing red triangle"], ["🔻", "down-pointing red triangle"], ["🔼", "up-pointing small red triangle"], ["🔽", "down-pointing small red triangle"],
      ["🕉️", "om symbol"], ["🕋", "kaaba"], ["🕌", "mosque"], ["🕍", "synagogue"],
      ["🕎", "menorah with nine branches"], ["🕐", "clock face one oclock"], ["🕑", "clock face two oclock"], ["🕒", "clock face three oclock"],
      ["🕓", "clock face four oclock"], ["🕔", "clock face five oclock"], ["🕕", "clock face six oclock"], ["🕖", "clock face seven oclock"],
      ["🕗", "clock face eight oclock"], ["🕘", "clock face nine oclock"], ["🕙", "clock face ten oclock"], ["🕚", "clock face eleven oclock"],
      ["🕛", "clock face twelve oclock"], ["🕜", "clock face one-thirty"], ["🕝", "clock face two-thirty"], ["🕞", "clock face three-thirty"],
      ["🕟", "clock face four-thirty"], ["🕠", "clock face five-thirty"], ["🕡", "clock face six-thirty"], ["🕢", "clock face seven-thirty"],
      ["🕣", "clock face eight-thirty"], ["🕤", "clock face nine-thirty"], ["🕥", "clock face ten-thirty"], ["🕦", "clock face eleven-thirty"],
      ["🕧", "clock face twelve-thirty"], ["🕯️", "candle"], ["🕰️", "mantelpiece clock"], ["🕳️", "hole"],
      ["🖤", "black heart"], ["🟠", "large orange circle"], ["🟡", "large yellow circle"], ["🟢", "large green circle"],
      ["🟣", "large purple circle"], ["🟤", "large brown circle"], ["🟥", "large red square"], ["🟦", "large blue square"],
      ["🟧", "large orange square"], ["🟨", "large yellow square"], ["🟩", "large green square"], ["🟪", "large purple square"],
      ["🟫", "large brown square"], ["🟰", "heavy equals sign"], ["🤌", "pinched fingers"], ["🤍", "white heart"],
      ["🤎", "brown heart"], ["🤏", "pinching hand"], ["🦯", "probing cane"], ["🩰", "ballet shoes"],
      ["🩱", "one-piece swimsuit"], ["🩲", "briefs"], ["🩳", "shorts"], ["🩴", "thong sandal"],
      ["🩵", "light blue heart"], ["🩶", "grey heart"], ["🩷", "pink heart"], ["🩸", "drop of blood"],
      ["🩹", "adhesive bandage"], ["🩺", "stethoscope"], ["🩻", "x-ray"], ["🩼", "crutch"],
      ["🫎", "moose"], ["🫏", "donkey"],
    ],
  },
  {
    id: "flags",
    label: "Flags",
    icon: "🏁",
    emojis: [
      ["🏁", "chequered flag"], ["🚩", "triangular flag"], ["🎌", "crossed flags"], ["🏴", "black flag"],
      ["🏳️", "white flag"], ["🏳️‍🌈", "rainbow flag pride"], ["🏴‍☠️", "pirate flag"], ["🇦🇨", "flag ascension island ac"],
      ["🇦🇩", "flag andorra ad"], ["🇦🇪", "flag united arab emirates ae"], ["🇦🇫", "flag afghanistan af"], ["🇦🇬", "flag antigua & barbuda ag"],
      ["🇦🇮", "flag anguilla ai"], ["🇦🇱", "flag albania al"], ["🇦🇲", "flag armenia am"], ["🇦🇴", "flag angola ao"],
      ["🇦🇶", "flag antarctica aq"], ["🇦🇷", "flag argentina ar"], ["🇦🇸", "flag american samoa as"], ["🇦🇹", "flag austria at"],
      ["🇦🇺", "flag australia au"], ["🇦🇼", "flag aruba aw"], ["🇦🇽", "flag aland islands ax"], ["🇦🇿", "flag azerbaijan az"],
      ["🇧🇦", "flag bosnia & herzegovina ba"], ["🇧🇧", "flag barbados bb"], ["🇧🇩", "flag bangladesh bd"], ["🇧🇪", "flag belgium be"],
      ["🇧🇫", "flag burkina faso bf"], ["🇧🇬", "flag bulgaria bg"], ["🇧🇭", "flag bahrain bh"], ["🇧🇮", "flag burundi bi"],
      ["🇧🇯", "flag benin bj"], ["🇧🇱", "flag st barthelemy bl"], ["🇧🇲", "flag bermuda bm"], ["🇧🇳", "flag brunei bn"],
      ["🇧🇴", "flag bolivia bo"], ["🇧🇶", "flag caribbean netherlands bq"], ["🇧🇷", "flag brazil br"], ["🇧🇸", "flag bahamas bs"],
      ["🇧🇹", "flag bhutan bt"], ["🇧🇻", "flag bouvet island bv"], ["🇧🇼", "flag botswana bw"], ["🇧🇾", "flag belarus by"],
      ["🇧🇿", "flag belize bz"], ["🇨🇦", "flag canada ca"], ["🇨🇨", "flag cocos islands cc"], ["🇨🇩", "flag congo kinshasa cd"],
      ["🇨🇫", "flag central african republic cf"], ["🇨🇬", "flag congo brazzaville cg"], ["🇨🇭", "flag switzerland ch"], ["🇨🇮", "flag cote d'ivoire ivory coast ci"],
      ["🇨🇰", "flag cook islands ck"], ["🇨🇱", "flag chile cl"], ["🇨🇲", "flag cameroon cm"], ["🇨🇳", "flag china cn"],
      ["🇨🇴", "flag colombia co"], ["🇨🇵", "flag clipperton island cp"], ["🇨🇷", "flag costa rica cr"], ["🇨🇺", "flag cuba cu"],
      ["🇨🇻", "flag cape verde cv"], ["🇨🇼", "flag curacao cw"], ["🇨🇽", "flag christmas island cx"], ["🇨🇾", "flag cyprus cy"],
      ["🇨🇿", "flag czechia czech republic cz"], ["🇩🇪", "flag germany de"], ["🇩🇬", "flag diego garcia dg"], ["🇩🇯", "flag djibouti dj"],
      ["🇩🇰", "flag denmark dk"], ["🇩🇲", "flag dominica dm"], ["🇩🇴", "flag dominican republic do"], ["🇩🇿", "flag algeria dz"],
      ["🇪🇦", "flag ceuta & melilla ea"], ["🇪🇨", "flag ecuador ec"], ["🇪🇪", "flag estonia ee"], ["🇪🇬", "flag egypt eg"],
      ["🇪🇭", "flag western sahara eh"], ["🇪🇷", "flag eritrea er"], ["🇪🇸", "flag spain es"], ["🇪🇹", "flag ethiopia et"],
      ["🇪🇺", "flag european union eu"], ["🇫🇮", "flag finland fi"], ["🇫🇯", "flag fiji fj"], ["🇫🇰", "flag falkland islands fk"],
      ["🇫🇲", "flag micronesia fm"], ["🇫🇴", "flag faroe islands fo"], ["🇫🇷", "flag france fr"], ["🇬🇦", "flag gabon ga"],
      ["🇬🇧", "flag united kingdom uk britain gb"], ["🇬🇩", "flag grenada gd"], ["🇬🇪", "flag georgia ge"], ["🇬🇫", "flag french guiana gf"],
      ["🇬🇬", "flag guernsey gg"], ["🇬🇭", "flag ghana gh"], ["🇬🇮", "flag gibraltar gi"], ["🇬🇱", "flag greenland gl"],
      ["🇬🇲", "flag gambia gm"], ["🇬🇳", "flag guinea gn"], ["🇬🇵", "flag guadeloupe gp"], ["🇬🇶", "flag equatorial guinea gq"],
      ["🇬🇷", "flag greece gr"], ["🇬🇸", "flag south georgia gs"], ["🇬🇹", "flag guatemala gt"], ["🇬🇺", "flag guam gu"],
      ["🇬🇼", "flag guinea-bissau gw"], ["🇬🇾", "flag guyana gy"], ["🇭🇰", "flag hong kong hk"], ["🇭🇲", "flag heard & mcdonald islands hm"],
      ["🇭🇳", "flag honduras hn"], ["🇭🇷", "flag croatia hr"], ["🇭🇹", "flag haiti ht"], ["🇭🇺", "flag hungary hu"],
      ["🇮🇨", "flag canary islands ic"], ["🇮🇩", "flag indonesia id"], ["🇮🇪", "flag ireland ie"], ["🇮🇱", "flag israel il"],
      ["🇮🇲", "flag isle of man im"], ["🇮🇳", "flag india in"], ["🇮🇴", "flag british indian ocean territory io"], ["🇮🇶", "flag iraq iq"],
      ["🇮🇷", "flag iran ir"], ["🇮🇸", "flag iceland is"], ["🇮🇹", "flag italy it"], ["🇯🇪", "flag jersey je"],
      ["🇯🇲", "flag jamaica jm"], ["🇯🇴", "flag jordan jo"], ["🇯🇵", "flag japan jp"], ["🇰🇪", "flag kenya ke"],
      ["🇰🇬", "flag kyrgyzstan kg"], ["🇰🇭", "flag cambodia kh"], ["🇰🇮", "flag kiribati ki"], ["🇰🇲", "flag comoros km"],
      ["🇰🇳", "flag st kitts & nevis kn"], ["🇰🇵", "flag north korea kp"], ["🇰🇷", "flag south korea kr"], ["🇰🇼", "flag kuwait kw"],
      ["🇰🇾", "flag cayman islands ky"], ["🇰🇿", "flag kazakhstan kz"], ["🇱🇦", "flag laos la"], ["🇱🇧", "flag lebanon lb"],
      ["🇱🇨", "flag st lucia lc"], ["🇱🇮", "flag liechtenstein li"], ["🇱🇰", "flag sri lanka lk"], ["🇱🇷", "flag liberia lr"],
      ["🇱🇸", "flag lesotho ls"], ["🇱🇹", "flag lithuania lt"], ["🇱🇺", "flag luxembourg lu"], ["🇱🇻", "flag latvia lv"],
      ["🇱🇾", "flag libya ly"], ["🇲🇦", "flag morocco ma"], ["🇲🇨", "flag monaco mc"], ["🇲🇩", "flag moldova md"],
      ["🇲🇪", "flag montenegro me"], ["🇲🇫", "flag st martin mf"], ["🇲🇬", "flag madagascar mg"], ["🇲🇭", "flag marshall islands mh"],
      ["🇲🇰", "flag north macedonia mk"], ["🇲🇱", "flag mali ml"], ["🇲🇲", "flag myanmar burma mm"], ["🇲🇳", "flag mongolia mn"],
      ["🇲🇴", "flag macao mo"], ["🇲🇵", "flag northern mariana islands mp"], ["🇲🇶", "flag martinique mq"], ["🇲🇷", "flag mauritania mr"],
      ["🇲🇸", "flag montserrat ms"], ["🇲🇹", "flag malta mt"], ["🇲🇺", "flag mauritius mu"], ["🇲🇻", "flag maldives mv"],
      ["🇲🇼", "flag malawi mw"], ["🇲🇽", "flag mexico mx"], ["🇲🇾", "flag malaysia my"], ["🇲🇿", "flag mozambique mz"],
      ["🇳🇦", "flag namibia na"], ["🇳🇨", "flag new caledonia nc"], ["🇳🇪", "flag niger ne"], ["🇳🇫", "flag norfolk island nf"],
      ["🇳🇬", "flag nigeria ng"], ["🇳🇮", "flag nicaragua ni"], ["🇳🇱", "flag netherlands nl"], ["🇳🇴", "flag norway no"],
      ["🇳🇵", "flag nepal np"], ["🇳🇷", "flag nauru nr"], ["🇳🇺", "flag niue nu"], ["🇳🇿", "flag new zealand nz"],
      ["🇴🇲", "flag oman om"], ["🇵🇦", "flag panama pa"], ["🇵🇪", "flag peru pe"], ["🇵🇫", "flag french polynesia pf"],
      ["🇵🇬", "flag papua new guinea pg"], ["🇵🇭", "flag philippines ph"], ["🇵🇰", "flag pakistan pk"], ["🇵🇱", "flag poland pl"],
      ["🇵🇲", "flag st pierre & miquelon pm"], ["🇵🇳", "flag pitcairn islands pn"], ["🇵🇷", "flag puerto rico pr"], ["🇵🇸", "flag palestine ps"],
      ["🇵🇹", "flag portugal pt"], ["🇵🇼", "flag palau pw"], ["🇵🇾", "flag paraguay py"], ["🇶🇦", "flag qatar qa"],
      ["🇷🇪", "flag reunion re"], ["🇷🇴", "flag romania ro"], ["🇷🇸", "flag serbia rs"], ["🇷🇺", "flag russia ru"],
      ["🇷🇼", "flag rwanda rw"], ["🇸🇦", "flag saudi arabia sa"], ["🇸🇧", "flag solomon islands sb"], ["🇸🇨", "flag seychelles sc"],
      ["🇸🇩", "flag sudan sd"], ["🇸🇪", "flag sweden se"], ["🇸🇬", "flag singapore sg"], ["🇸🇭", "flag st helena sh"],
      ["🇸🇮", "flag slovenia si"], ["🇸🇯", "flag svalbard & jan mayen sj"], ["🇸🇰", "flag slovakia sk"], ["🇸🇱", "flag sierra leone sl"],
      ["🇸🇲", "flag san marino sm"], ["🇸🇳", "flag senegal sn"], ["🇸🇴", "flag somalia so"], ["🇸🇷", "flag suriname sr"],
      ["🇸🇸", "flag south sudan ss"], ["🇸🇹", "flag sao tome & principe st"], ["🇸🇻", "flag el salvador sv"], ["🇸🇽", "flag sint maarten sx"],
      ["🇸🇾", "flag syria sy"], ["🇸🇿", "flag eswatini swaziland sz"], ["🇹🇦", "flag tristan da cunha ta"], ["🇹🇨", "flag turks & caicos islands tc"],
      ["🇹🇩", "flag chad td"], ["🇹🇫", "flag french southern territories tf"], ["🇹🇬", "flag togo tg"], ["🇹🇭", "flag thailand th"],
      ["🇹🇯", "flag tajikistan tj"], ["🇹🇰", "flag tokelau tk"], ["🇹🇱", "flag timor-leste tl"], ["🇹🇲", "flag turkmenistan tm"],
      ["🇹🇳", "flag tunisia tn"], ["🇹🇴", "flag tonga to"], ["🇹🇷", "flag turkey turkiye tr"], ["🇹🇹", "flag trinidad & tobago tt"],
      ["🇹🇻", "flag tuvalu tv"], ["🇹🇼", "flag taiwan tw"], ["🇹🇿", "flag tanzania tz"], ["🇺🇦", "flag ukraine ua"],
      ["🇺🇬", "flag uganda ug"], ["🇺🇲", "flag us outlying islands um"], ["🇺🇳", "flag united nations un"], ["🇺🇸", "flag united states usa america us"],
      ["🇺🇾", "flag uruguay uy"], ["🇺🇿", "flag uzbekistan uz"], ["🇻🇦", "flag vatican city va"], ["🇻🇨", "flag st vincent & grenadines vc"],
      ["🇻🇪", "flag venezuela ve"], ["🇻🇬", "flag british virgin islands vg"], ["🇻🇮", "flag us virgin islands vi"], ["🇻🇳", "flag vietnam vn"],
      ["🇻🇺", "flag vanuatu vu"], ["🇼🇫", "flag wallis & futuna wf"], ["🇼🇸", "flag samoa ws"], ["🇽🇰", "flag kosovo xk"],
      ["🇾🇪", "flag yemen ye"], ["🇾🇹", "flag mayotte yt"], ["🇿🇦", "flag south africa za"], ["🇿🇲", "flag zambia zm"],
      ["🇿🇼", "flag zimbabwe zw"],
    ],
  },
];